#!/usr/bin/env docker.sh

name=postgres
image=postgres:11
opts="
  -p 5432:5432
  -e POSTGRES_PASSWORD=password
  -e POSTGRES_USER=luaja
  -e POSTGRES_DB=luaja
  -v $dir/pgdata:/var/lib/postgresql/data
"

command_killme() {
  rm -rf $dir/pgdata
  "$dir/postgres" restart
}