version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /luaja
    
    steps:
      - checkout
      - restored_cache:
          keys:
            - luaja-cache
      - run: go mod init
      - run: go mod tidy
      - save_cache:
          key: luaja-cache
          paths:
            - "/go/pkg"
      - run: go test ./...


