version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/payfazz/luaja
    
    steps:
      - checkout
      - run: go mod download
      - run: go test ./...


